### ISSUE TITLE
引用错误

### ISSUE THREAD

**Issue by WingDust** [siaikin/sync-scroll#2]
![image](https://user-images.githubusercontent.com/45911286/69478953-2845b780-0e33-11ea-8cf5-87c3df535124.png)

我使用eletron 引用 是ES6 的原因还是另有原因

**Comment by siaikin** [comment]
根据报错信息显示浏览器无法解析es6的import语法，一般我们都是用webpack打包后再放到浏览器里执行的，如果你不想使用webpack，可以将 <script> 的 type 设置为 module。

如下代码所示：
```html
<script type="module" src="xxxx"></script>
```
